<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ExchangeRate;


/**
 * ExchangeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRateRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateExchangeRateCommand($data){
        foreach ($data as $key => $value){
            $this->getEntityManager()->createQueryBuilder()
                ->update(ExchangeRate::class, 'exchangerate')
                ->set('exchangerate.rate', ':rate')
                ->where('exchangerate.code = :code')
                ->setParameters([
                    'rate' => $value,
                    'code' => $key,
                ])
                ->getQuery()
                ->execute()
            ;
        }
    }
}
