<?php

namespace AppBundle\Repository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllToArray($id){
        $results = $this->createQueryBuilder('model')
            ->select('model.id, model.name')
            ->join('model.brand', 'brand')
            ->where('brand.id = :id')
            ->setParameters([
                'id' => $id
            ])
            ->getQuery()
            ->getArrayResult()
        ;

        return $results;
    }

}
