<?php

namespace AppBundle\Repository;

/**
 * SparePartCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SparePartCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneBySlug($slug){
        $results = $this
        ->createQueryBuilder('sparePartCategory')
            ->join('sparepartcategory.translations', 'translations')
            ->where('translations.slug = :slug')
            ->setParameters([
                'slug' => $slug
            ])
            ->getQuery()
            ->getOneOrNullResult()
        ;
        return $results;

    }
}
