<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ExchangeRate;


/**
 * TaxeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxeRateRepository extends \Doctrine\ORM\EntityRepository
{

}
